package com.chiguru.pm.tax.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

// Generated Dec 6, 2010 12:16:20 AM by Hibernate Tools 3.3.0.GA
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.chiguru.pm.core.common.domain.PersistentEntity;

/**
 * TaxApplicationPracticeType generated by hbm2java
 */
@Entity
@Table(name = "tax_application_practice_type")
public class PracticeType extends PersistentEntity implements java.io.Serializable {
//    private Long id;
    
	@NotEmpty
    @Size(min = 0, max = 50)
    @Pattern(regexp = "^[a-zA-Z.\\s]*$")
    private String name;
    
    @Size(min = 0, max = 100)
    @Pattern(regexp = "^[a-zA-Z.\\s]*$")
    private String description;
    private Boolean applicationLevel;

    //private Set<TaxFirmPracticeType> taxFirmPracticeTypes = new HashSet<TaxFirmPracticeType>(
    //		0);

//    public boolean activeFlag;
//    public Date createDate = new Date();
//    public String createUserId;

    public PracticeType() {
    }

    public PracticeType(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public PracticeType(String name, String description,
        Boolean applicationLevel) {
        //Set<TaxFirmPracticeType> taxFirmPracticeTypes) {
        this.name = name;
        this.description = description;
        this.applicationLevel = applicationLevel;

        //this.taxFirmPracticeTypes = taxFirmPracticeTypes;
    }

    /*@Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }*/

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", nullable = false, length = 200)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "application_level")
    public Boolean getApplicationLevel() {
        return this.applicationLevel;
    }

    public void setApplicationLevel(Boolean applicationLevel) {
        this.applicationLevel = applicationLevel;
    }

    /*@Column(name = "active_flag", nullable = false)
    public boolean isActiveFlag() {
        return activeFlag;
    }

    public void setActiveFlag(boolean activeFlag) {
        this.activeFlag = activeFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "create_user_id", nullable = false, length = 25)
    public String getCreateUserId() {
        return createUserId;
    }

    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }*/

    //	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxApplicationPracticeType")
    //	public Set<TaxFirmPracticeType> getTaxFirmPracticeTypes() {
    //		return this.taxFirmPracticeTypes;
    //	}
    //
    //	public void setTaxFirmPracticeTypes(
    //			Set<TaxFirmPracticeType> taxFirmPracticeTypes) {
    //		this.taxFirmPracticeTypes = taxFirmPracticeTypes;
    //	}
}
