package com.chiguru.pm.tax.domain;


// Generated Dec 29, 2010 10:46:55 PM by Hibernate Tools 3.3.0.GA
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.chiguru.pm.core.common.domain.PersistentEntity;


/**
 * TaxInfoFilingType generated by hbm2java
 */

@Entity
@Table(name = "task_notification_template")
public class TaskNotificationTemplate extends PersistentEntity implements java.io.Serializable {	
	
// 	private Long id;
	@NotEmpty
    @Size(min = 0, max = 4000)
//	@Pattern(regexp = "^[0-9a-zA-Z-.,@:%\\s]*$") 
    private String subject;
	
	@NotEmpty
    @Size(min = 0, max = 4000)
//	@Pattern(regexp = "^[0-9a-zA-Z-.,@:%\\s]*$") 
    private String bodyText;
	
	@NotEmpty
    @Size(min = 0, max = 400)
//    @Pattern( regexp="^[[a-zA-Z0-9._-]+@[a-zA-Z0-9]+([.-]?[a-zA-Z0-9]+)?([\\.]{1}[a-zA-Z]{2,4}){1,4}]*$")  //@Pattern is commented bcoz Regular Expression for sever side validation is not accepting multiple emails   
  	private String adminEmailId;

    public TaskNotificationTemplate() {
    }

    public TaskNotificationTemplate(Long id) {
        this.id = id;       
    }

    public TaskNotificationTemplate(String subject, String bodyText) {
        this.subject = subject;
        this.bodyText = bodyText;
    }

   

    /*@Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)    
	public Long getId() {
		return id;
	}

	*//**
	 * @param id the id to set
	 *//*
	public void setId(Long id) {
		this.id = id;
	}*/
	
	/**
	 * @return the adminEmailId
	 */
	@Column(name = "additional_emailId", unique = true, nullable = false)
	public String getAdminEmailId() {
		return adminEmailId;
	}

	/**
	 * @param adminEmailId the adminEmailId to set
	 */
	public void setAdminEmailId(String adminEmailId) {
		this.adminEmailId = adminEmailId;
	}
    /**
	 * @return the subject
	 */
    @Column(name = "subject", length = 10)
	public String getSubject() {
		return subject;
	}

	/**
	 * @param subject the subject to set
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * @return the bodyText
	 */
	@Column(name = "body", length = 10)
	public String getBodyText() {
		return bodyText;
	}

	/**
	 * @param bodyText the bodyText to set
	 */
	public void setBodyText(String bodyText) {
		this.bodyText = bodyText;
	}

	@Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }

        if (!(obj instanceof TaskNotificationRecipient)) {
            return false;
        }

        TaskNotificationRecipient other = (TaskNotificationRecipient) obj;

        return getId().equals(other.getId());
    }
}
