package com.chiguru.pm.tax.domain;


// Generated Jun 9, 2010 9:02:16 PM by Hibernate Tools 3.3.0.GA
import java.util.Date;

import com.chiguru.pm.crm.domain.Organization;
import com.chiguru.pm.crm.domain.Person;

/**
 * Code generated by hbm2java
 */

public class TaskRep implements java.io.Serializable {
   
	public String days;
	public String dueDate1;
	public String dueDate2;
	public String sortType;
	public String dateRange;
	private Person partnerInCharge;
	private PracticeType tasklistname;
	private Organization firmList;
	public TaxInfoFilingType filingTypeList;
	public TaskStatus statusList;
	public String viewAs;
	public String sortAs;
	public String inCharge;
	public Date from;
	public Date to;
	public Integer taskStatusId;
	public Integer filingType;
	public String pIC;
	
    public TaskRep() {
    }
    
	/**
	 * @return the virwAs
	 */
    public String getPIC(){
    	return pIC;
    }
    
    public Integer getTaskStatusId() {
		return taskStatusId;
	}
    
    public Integer getFilingType() {
		return filingType;
	}
    
	public String getViewAs() {
		return viewAs;
	}
     
	public String getSortAs(){
		return sortAs;
	}

	public String getInCharge(){
		return inCharge;
	}

	public Date getFrom(){
		return from;
	}
	public Date getTo(){
		return to;
	}
	/**
	 * @param virwAs the virwAs to set
	 */
	public void setPIC(String pIC){
		this.pIC = pIC;
	}
	public void setTaskStatusId(Integer taskStatusId) {
		this.taskStatusId = taskStatusId;
	}
	
	public void setFilingType(Integer filingType) {
		this.filingType = filingType;
	}
	
	public void setViewAs(String viewAs) {
		this.viewAs = viewAs;
	}

   public void setSortAs(String sortAs){
	   this.sortAs = sortAs;
   }
   
   public void setInCharge(String inCharge){
	   this.inCharge = inCharge;
   }
 
   public void setFrom(Date from){
	   this.from = from;
   }
   
   public void setTo(Date to){
	   this.to = to;
   }
	/**
	 * @return the statusList
	 */
	public TaskStatus getStatusList() {
		return statusList;
	}


	/**
	 * @param statusList the statusList to set
	 */
	public void setStatusList(TaskStatus statusList) {
		this.statusList = statusList;
	}


	/**
	 * @return the filingTypeList
	 */
	public TaxInfoFilingType getFilingTypeList() {
		return filingTypeList;
	}


	/**
	 * @param filingTypeList the filingTypeList to set
	 */
	public void setFilingTypeList(TaxInfoFilingType filingTypeList) {
		this.filingTypeList = filingTypeList;
	}


	/**
	 * @return the firmList
	 */
	public Organization getFirmList() {
		return firmList;
	}



	/**
	 * @param firmList the firmList to set
	 */
	public void setFirmList(Organization firmList) {
		this.firmList = firmList;
	}



	/**
	 * @return the tasklistname
	 */
	public PracticeType getTasklistname() {
		return tasklistname;
	}


	/**
	 * @param tasklistname the tasklistname to set
	 */
	public void setTasklistname(PracticeType tasklistname) {
		this.tasklistname = tasklistname;
	}


	/**
	 * @return the partnerInCharge
	 */
	public Person getPartnerInCharge() {
		return partnerInCharge;
	}


	/**
	 * @param partnerInCharge the partnerInCharge to set
	 */
	public void setPartnerInCharge(Person partnerInCharge) {
		this.partnerInCharge = partnerInCharge;
	}


	/**
	 * @return the dateRange
	 */
	public String getDateRange() {
		return dateRange;
	}

	/**
	 * @param dateRange the dateRange to set
	 */
	public void setDateRange(String dateRange) {
		this.dateRange = dateRange;
	}

	/**
	 * @return the days
	 */
	public String getDays() {
		return days;
	}
	/**
	 * @param days the days to set
	 */
	public void setDays(String days) {
		this.days = days;
	}
	/**
	 * @return the dueDate1
	 */
	public String getDueDate1() {
		return dueDate1;
	}
	/**
	 * @param dueDate1 the dueDate1 to set
	 */
	public void setDueDate1(String dueDate1) {
		this.dueDate1 = dueDate1;
	}
	/**
	 * @return the dueDate2
	 */
	public String getDueDate2() {
		return dueDate2;
	}
	/**
	 * @param dueDate2 the dueDate2 to set
	 */
	public void setDueDate2(String dueDate2) {
		this.dueDate2 = dueDate2;
	}
	/**
	 * @return the sortType
	 */
	public String getSortType() {
		return sortType;
	}
	/**
	 * @param sortType the sortType to set
	 */
	public void setSortType(String sortType) {
		this.sortType = sortType;
	}  
    
    
}
