package com.chiguru.pm.tax.domain;


// Generated Dec 29, 2010 10:46:55 PM by Hibernate Tools 3.3.0.GA
import com.chiguru.pm.core.common.domain.PersistentEntity;


/**
 * TaxInfoFilingType generated by hbm2java
 */

//@Entity
//@Table(name = "tax_info_filing_type")
public class TaxInfoFilingType extends PersistentEntity implements java.io.Serializable {
    public static final TaxInfoFilingType TAX_FILING_TYPE = new TaxInfoFilingType(new Long(
                1));
    public static final TaxInfoFilingType INSTALLMENT_FILING_TYPE = new TaxInfoFilingType(new Long(
                2));
    private String name;
    private String description;

    public TaxInfoFilingType() {
    }

    public TaxInfoFilingType(Long id) {
        this.id = id;

        if (id == 1) {
            this.name = "Tax Filing Type";
        } else {
            this.name = "Installment Filing Type";
        }
    }

    public TaxInfoFilingType(String name, String description) {
        this.name = name;
        this.description = description;
    }

    //@Column(name = "name", length = 40)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    //@Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }

        if (!(obj instanceof TaxInfoFilingType)) {
            return false;
        }

        TaxInfoFilingType other = (TaxInfoFilingType) obj;

        return getId().equals(other.getId());
    }
}
