package com.chiguru.pm.crm.domain;

import com.chiguru.pm.core.common.domain.PersistentEntity;

// Generated Jun 9, 2010 9:02:16 PM by Hibernate Tools 3.3.0.GA
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address")
public class Address extends PersistentEntity implements java.io.Serializable {
    //private Long id;
	
//	@NotNull
	/*@NotEmpty
    @Size(min = 0, max = 100)
    @Pattern(regexp = "^\\s*[a-zA-Z0-9.\\s-_#&{},.;]+\\s*$")*/
    private String addressLine1;
	
	/*@Size(min = 0, max = 100)
	@Pattern(regexp = "^\\s*[a-zA-Z0-9.\\s-_#&{},.;]+\\s*$")*/
    private String addressLine2;

  //  @NotNull
	/*@NotEmpty
	@Size(min = 0, max = 100)
	@Pattern(regexp = "^\\s*[a-zA-Z.\\s]+\\s*$")*/
    private String city;

	//@NotEmpty
    private Long stateCode;
    
	//@NotEmpty
    private Long countryCode;
    
   // @NotNull
	/*@NotEmpty
    @Size(min = 0, max = 7)
    @Pattern(regexp = "^[A-Z][0-9][A-Z]\\s[0-9][A-Z][0-9]$")*/
    private String postalCode;
    private PartySite partySite;

    public Address() {
//        setCreateUserId("system");
    }

    public Address(String addressLine1, String addressLine2, String city,
        Long stateCode, String postalCode, Long countryCode, PartySite partySite) {
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.city = city;
        this.stateCode = stateCode;
        this.postalCode = postalCode;
        this.countryCode = countryCode;
        this.partySite = partySite;
//        setCreateUserId("system");
    }

    //	@Id
    //	@GeneratedValue(strategy = IDENTITY)
    //	@Column(name = "id", unique = true, nullable = false)
    //	public Long getId() {
    //		return this.id;
    //	}
    //
    //	public void setId(Long id) {
    //		this.id = id;
    //	}
    @Column(name = "address_line_1", length = 100)
    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    @Column(name = "address_line_2", length = 100)
    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    @Column(name = "city", length = 100)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

/*    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "state_code")
*/    
    @Column(name = "state_code")
    public Long getStateCode() {
        return this.stateCode;
    }

    public void setStateCode(Long stateCode) {
        this.stateCode = stateCode;
    }

    @Column(name = "postal_code", length = 50)
    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

   /* @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "country_code")*/
    @Column(name = "country_code")
    public Long getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(Long countryCode) {
        this.countryCode = countryCode;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "address")
    public PartySite getPartySite() {
        return this.partySite;
    }

    public void setPartySite(PartySite partySite) {
        this.partySite = partySite;
    }
}
