package com.chiguru.pm.crm.domain;


// Generated Jun 9, 2010 9:02:16 PM by Hibernate Tools 3.3.0.GA
//import java.util.regex.Matcher;
//import java.util.regex.Pattern;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotEmpty;

import com.chiguru.pm.core.common.domain.PersistentEntity;


/**
 * Jurisdiction generated by hbm2java
 */
@Entity
@Table(name = "jurisdiction")
public class Jurisdiction extends PersistentEntity  implements java.io.Serializable {
    //private Integer id;
	@NotEmpty
    @Size(min = 0, max = 50)
    @Pattern(regexp = "^[a-zA-Z ]*$")
    private String country;
	
	@NotEmpty
    @Size(min = 0, max = 50)
   @Pattern(regexp = "^[a-zA-Z ]*$")
   private String state;
	
	@NotEmpty
	@Size(min = 0, max = 50)
	@Pattern(regexp = "^[a-zA-Z ]*$")
    private String county;
	
	@NotEmpty
	@Size(min = 0, max = 50)
	@Pattern(regexp = "^[a-zA-Z ]*$")
    private String city;
	
//  private Set<Party> parties = new HashSet<Party>(0);
//     @Valid
//	@NotEmpty
	@NotNull
    private Timezone timezone;

    //	@Id
    //	@Column(name = "id", unique = true, nullable = false)
    //	public Integer getId() {
    //		return this.id;
    //	}
    //
    //	public void setId(Integer id) {
    //		this.id = id;
    //	}
    @Column(name = "country", length = 50)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
    
        this.country = country;
    }

    @Column(name = "state", length = 50)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "county", length = 50)
    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    @Column(name = "city", length = 50)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String toString() {
        StringBuffer sb = (country != null) ? new StringBuffer(country)
                                            : new StringBuffer("");

        if (state != null) {
            sb.append(":" + state);
        }

        /*if (county != null) {
            sb.append(":" + county);
        }

        if (city != null) {
            sb.append(":" + city);
        }*/

        return sb.toString();
    } 

    @Transient
    public String getName() {
        return this.toString();
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "timezone", nullable = false)
    public Timezone getTimezone() {
        return this.timezone;
    }

    public void setTimezone(Timezone timezone) {
        this.timezone = timezone;
    }

    //@OneToMany(fetch = FetchType.LAZY, mappedBy = "jurisdiction")
    //	public Set<Party> getParties() {
    //	return this.parties;
    //}

    //public void setParties(Set<Party> parties) {
    //	this.parties = parties;
    //}
    
    /*public static boolean isStringValid(String value){
    	boolean isValid = false;
    	String expression = "^[0-9A-Z-]+$";
    	CharSequence inputStr = value;
    	Pattern pattern = Pattern.compile(expression);
    	Matcher matcher = pattern.matcher(inputStr);
    	if(matcher.matches()){
    		isValid = true;
    	}
    	return isValid;
    }*/

}
