package com.chiguru.pm.crm.domain;

import com.chiguru.pm.core.common.domain.ReadOnlyEntity;

// Generated Jun 9, 2010 9:02:16 PM by Hibernate Tools 3.3.0.GA
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language extends ReadOnlyEntity implements java.io.Serializable {
    //private Integer id;
    private String name;
    private String languageCode;
    private String utf8DateLanguage;
    private Set<Party> parties = new HashSet<Party>(0);

    public Language() {
    }

    public Language(Integer id) {
        this.id = id;
    }

    public Language(Integer id, String name, String languageCode,
        String utf8DateLanguage, Set<Party> parties) {
        this.id = id;
        this.name = name;
        this.languageCode = languageCode;
        this.utf8DateLanguage = utf8DateLanguage;
        this.parties = parties;
    }

    //	@Id
    //	@Column(name = "id", unique = true, nullable = false)
    //	public Integer getId() {
    //		return this.id;
    //	}
    //
    //	public void setId(Integer id) {
    //		this.id = id;
    //	}
    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "language_code", length = 25)
    public String getLanguageCode() {
        return this.languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    @Column(name = "utf8_date_language", length = 50)
    public String getUtf8DateLanguage() {
        return this.utf8DateLanguage;
    }

    public void setUtf8DateLanguage(String utf8DateLanguage) {
        this.utf8DateLanguage = utf8DateLanguage;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<Party> getParties() {
        return this.parties;
    }

    public void setParties(Set<Party> parties) {
        this.parties = parties;
    }
}
