package com.chiguru.pm.crm.domain;

import com.chiguru.pm.core.common.domain.ReadOnlyEntity;

// Generated Jun 9, 2010 9:02:16 PM by Hibernate Tools 3.3.0.GA
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.Valid;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;


/**
 * PartyType generated by hbm2java
 */
@Entity
@Table(name = "party_site_type")
public class PartySiteType extends ReadOnlyEntity implements Serializable {
//	@Valid
    public static Integer MAIN_OFFICE_PARTY_SITE_TYPE = 1;
    public static Integer BRANCH_OFFICE_PARTY_SITE_TYPE = 2;
    public static Integer HOME_PARTY_SITE_TYPE = 3;
    public static Integer AGENCY_PARTY_SITE_TYPE = 8;
    private Boolean defaultFlag;
//    @NotEmpty
//    @Size(min = 0, max = 50)
//    @Pattern(regexp = "^[a-zA-Z.\\s]*$")
    private String name;
    private String description;

    public PartySiteType() {
    }

    public PartySiteType(Boolean defaultFlag) {
        this.defaultFlag = defaultFlag;
    }

    public PartySiteType(Integer id) {
        this.id = id;
    }

    public PartySiteType(Integer id, Boolean defaultFlag, String name) {
        this.id = id;
        this.defaultFlag = defaultFlag;
        this.name = name;
    }

    /**
     * @return the name
     */
    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the description
     */
    @Column(name = "description", length = 100)
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the default flag
     */
    @Column(name = "default_flag")
    public Boolean isDefaultFlag() {
        return defaultFlag;
    }

    /**
     * @param phoneIndicator the phoneIndicator to set
     */
    public void setDefaultFlag(Boolean defaultFlag) {
        this.defaultFlag = defaultFlag;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }

        if (!(obj instanceof PartySiteType)) {
            return false;
        }

        PartySiteType other = (PartySiteType) obj;

        if (getId().intValue() != other.getId().intValue()) {
            return false;
        }

        return true;
    }
}
