package com.chiguru.pm.crm.domain;

import com.chiguru.pm.core.common.domain.ReadOnlyEntity;

// Generated Jun 9, 2010 9:02:16 PM by Hibernate Tools 3.3.0.GA
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * PartyType generated by hbm2java
 */
@Entity
@Table(name = "share_type")
public class ShareType extends ReadOnlyEntity implements Serializable {
    public static int ORDINARY_SHARE_TYPE = 1;
    public static int PREFERRED_SHARE_TYPE = 2;
    public static int OTHER_SHARE_TYPE = 3;
    private Boolean shareIndicator;
    private String name;
    private String description;

    public ShareType() {
    }

    public ShareType(Integer id) {
        this.id = id;
    }

    public ShareType(Integer id, Boolean phoneIndicator, String name) {
        this.id = id;
        this.shareIndicator = phoneIndicator;
        this.name = name;
    }

    /**
     * @return the name
     */
    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the description
     */
    @Column(name = "description", length = 100)
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the phoneIndicator
     */
    @Column(name = "share_indicator")
    public Boolean getPhoneIndicator() {
        return shareIndicator;
    }

    /**
     * @param phoneIndicator the phoneIndicator to set
     */
    public void setPhoneIndicator(Boolean phoneIndicator) {
        this.shareIndicator = phoneIndicator;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }

        if (!(obj instanceof ShareType)) {
            return false;
        }

        ShareType other = (ShareType) obj;

        if (getId().intValue() != other.getId().intValue()) {
            return false;
        }

        return true;
    }
}
