package com.chiguru.pm.crm.domain;

import com.chiguru.pm.core.common.domain.PersistentEntity;

// Generated Jun 9, 2010 9:02:16 PM by Hibernate Tools 3.3.0.GA
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.NumberFormat;
import org.springframework.format.annotation.NumberFormat.Style;


/**
 * Timezone generated by hbm2java
 */
@Entity
@Table(name = "timezone")
public class Timezone extends PersistentEntity implements java.io.Serializable {
    //private Integer id;
	
//	@NotEmpty
//	@Pattern(regexp = "^[a-zA-Z.()&]*$",flags=Pattern.Flag.COMMENTS ,
//			message="No Special Character are allowed.. Enter valid Global Timezone Name")  //White Space must be allowed for this field, But its not allowing to add
    @Size(min = 0, max = 50)
     @Pattern(regexp = "^[a-zA-Z.\\s]*$")
    private String globalTimezoneName;
	
	/*@NotNull
	@NumberFormat(style = Style.NUMBER)
//	@Pattern(regexp = "^[0-9]*$")
    @Min(-24)
    @Max(+24)
    @Size(min = 0, max = 50)*/
    private Integer gmtDeviationHours;
    private Boolean dstFlag = true;
    
  /*  @NotNull
	@NumberFormat(style = Style.NUMBER)
//	@Pattern(regexp = "^[0-9]*$")
    @Min(0)
    @Max(12)*/
    private Short dstBeginMonth;
    /*
    @NotNull
	@NumberFormat(style = Style.NUMBER)
    @Min(0)
    @Max(32)*/
    private Short dstBeginDay;
    
    /*@NotNull
	@NumberFormat(style = Style.NUMBER)
    @Min(0)
    @Max(4)*/
    private Short dstBeginDayOfWeek;
    
   /* @NotNull
	@NumberFormat(style = Style.NUMBER)
    @Min(0)
    @Max(24)*/
    private Short dstBeginHour;
    
   /* @NotNull
	@NumberFormat(style = Style.NUMBER)
    @Min(0)
    @Max(12)*/
    private Short dstEndMonth;
    
   /* @NotNull
	@NumberFormat(style = Style.NUMBER)
    @Min(0)
    @Max(32)*/
    private Short dstEndDay;
    
    /*@NotNull
	@NumberFormat(style = Style.NUMBER)
    @Min(0)
    @Max(4)*/
    private Short dstEndDayOfWeek;
    
   /* @NotNull
	@NumberFormat(style = Style.NUMBER)
    @Min(0)
    @Max(24)*/
    private Short dstEndHour;
    
//    @NotEmpty
	@Size(min = 0, max = 5)
	@Pattern(regexp = "^[a-zA-Z.]*$",message="No Special Character are allowed.. Enter valid DST STD Code")
    private String dstStdCd;
    
//    @NotEmpty
	@Size(min = 0, max = 5)
	@Pattern(regexp = "^[a-zA-Z.]*$",message="No Special Character are allowed.. Enter valid DST Savings Code")
    private String dstSavingsCd;

    //	private Set<Party> parties = new HashSet<Party>(0);
    public Timezone() {
    }

    public Timezone(String globalTimezoneName, Integer gmtDeviationHours,
        Boolean dstFlag, Short dstBeginMonth, Short dstBeginDay,
        Short dstBeginDayOfWeek, Short dstBeginHour, Short dstEndMonth,
        Short dstEndDay, Short dstEndDayOfWeek, Short dstEndHour,
        String dstStdCd, String dstSavingsCd, Set<Party> parties) {
        this.globalTimezoneName = globalTimezoneName;
        this.gmtDeviationHours = gmtDeviationHours;
        this.dstFlag = dstFlag;
        this.dstBeginMonth = dstBeginMonth;
        this.dstBeginDay = dstBeginDay;
        this.dstBeginDayOfWeek = dstBeginDayOfWeek;
        this.dstBeginHour = dstBeginHour;
        this.dstEndMonth = dstEndMonth;
        this.dstEndDay = dstEndDay;
        this.dstEndDayOfWeek = dstEndDayOfWeek;
        this.dstEndHour = dstEndHour;
        this.dstStdCd = dstStdCd;
        this.dstSavingsCd = dstSavingsCd;

        //		this.parties = parties;
    }

    //	@Id
    //	@GeneratedValue(strategy = IDENTITY)
    //	@Column(name = "id", unique = true, nullable = false)
    //	public Integer getId() {
    //		return this.id;
    //	}
    //
    //	public void setId(Integer id) {
    //		this.id = id;
    //	}
    @Column(name = "global_timezone_name", length = 50)
    public String getGlobalTimezoneName() {
        return this.globalTimezoneName;
    }

    public void setGlobalTimezoneName(String globalTimezoneName) {
        this.globalTimezoneName = globalTimezoneName;
    }

    @Column(name = "gmt_deviation_hours")
    public Integer getGmtDeviationHours() {
        return this.gmtDeviationHours;
    }

    public void setGmtDeviationHours(Integer gmtDeviationHours) {
        this.gmtDeviationHours = gmtDeviationHours;
    }

    @Column(name = "dst_flag")
    public Boolean getDstFlag() {
        return this.dstFlag;
    }

    public void setDstFlag(Boolean dstFlag) {
        this.dstFlag = dstFlag;
    }

    @Column(name = "dst_begin_month")
    public Short getDstBeginMonth() {
        return this.dstBeginMonth;
    }

    public void setDstBeginMonth(Short dstBeginMonth) {
        this.dstBeginMonth = dstBeginMonth;
    }

    @Column(name = "dst_begin_day")
    public Short getDstBeginDay() {
        return this.dstBeginDay;
    }

    public void setDstBeginDay(Short dstBeginDay) {
        this.dstBeginDay = dstBeginDay;
    }

    @Column(name = "dst_begin_day_of_week")
    public Short getDstBeginDayOfWeek() {
        return this.dstBeginDayOfWeek;
    }

    public void setDstBeginDayOfWeek(Short dstBeginDayOfWeek) {
        this.dstBeginDayOfWeek = dstBeginDayOfWeek;
    }

    @Column(name = "dst_begin_hour")
    public Short getDstBeginHour() {
        return this.dstBeginHour;
    }

    public void setDstBeginHour(Short dstBeginHour) {
        this.dstBeginHour = dstBeginHour;
    }

    @Column(name = "dst_end_month")
    public Short getDstEndMonth() {
        return this.dstEndMonth;
    }

    public void setDstEndMonth(Short dstEndMonth) {
        this.dstEndMonth = dstEndMonth;
    }

    @Column(name = "dst_end_day")
    public Short getDstEndDay() {
        return this.dstEndDay;
    }

    public void setDstEndDay(Short dstEndDay) {
        this.dstEndDay = dstEndDay;
    }

    @Column(name = "dst_end_day_of_week")
    public Short getDstEndDayOfWeek() {
        return this.dstEndDayOfWeek;
    }

    public void setDstEndDayOfWeek(Short dstEndDayOfWeek) {
        this.dstEndDayOfWeek = dstEndDayOfWeek;
    }

    @Column(name = "dst_end_hour")
    public Short getDstEndHour() {
        return this.dstEndHour;
    }

    public void setDstEndHour(Short dstEndHour) {
        this.dstEndHour = dstEndHour;
    }

    @Column(name = "dst_std_cd", length = 5, nullable = true)
    public String getDstStdCd() {
        return this.dstStdCd;
    }

    public void setDstStdCd(String dstStdCd) {
        this.dstStdCd = dstStdCd;
    }

    @Column(name = "dst_savings_cd", length = 5, nullable = true)
    public String getDstSavingsCd() {
        return this.dstSavingsCd;
    }

    public void setDstSavingsCd(String dstSavingsCd) {
        this.dstSavingsCd = dstSavingsCd;
    }

    /*@OneToMany(fetch = FetchType.LAZY, mappedBy = "timezone")
    public Set<Party> getParties() {
            return this.parties;
    }
    
    public void setParties(Set<Party> parties) {
            this.parties = parties;
    }*/
}
